apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vote-service
  name: vote-service
spec:
  ports:
  - name: 5000-80
    port: 5000
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    run: vote-deployment
  type: NodePort