apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    app: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app-image
        image: kodekloud/examplevotingapp_vote:before
        ports:
        - containerPort: 3000


--- 

apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: vote
spec:
  ports:
  - name: 5000-80
    port: 5000
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote-deployment
  type: NodePort
