apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: grupo3
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.0.3
        args: ["--auth"]
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_ADMIN_PASSWORD
          value: clyde
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_DATABASE 
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_PASSWORD 
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_USER 
        volumeMounts:
          - name: mongo-db
            mountPath: /data/db
          - name : init-script
            mountPath: /docker-entrypoint-initdb.d
            readOnly: true
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: mongo-storage
        - name: init-script
          configMap:
             name: mongo-init-cm
             items:
              - key: mongo-init.sh
                path: mongo-init.sh   



